#ifndef TYPES__H
#define TYPES__H 1

#define MAX_STR 30

typedef enum {
	TRUE,
	FALSE
} bool_t;

typedef enum {
	ST_OK,
	ST_ERROR_PUNTERO_NULO,
	ST_ERROR_CANTIDAD_ARGUMENTOS,
	ST_ERROR_MEMORIA_INVALIDA,
	ST_ERROR_ENTRADA_INVALIDA,
	ST_ERROR_CARACTER_INCORRECTO_MEMORIA,
	ST_ERROR_FILE_INPUT_DEMASIADO_LARGO,
	ST_ERROR_INPUT_EXTENSION_INCORRECTA,
	ST_ERROR_BIN_INPUT_INCORRECTO,
	ST_ERROR_FILE_OUTPUT_DEMASIADO_LARGO,
	ST_ERROR_OUTPUT_EXTENSION_INCORRECTA,
	ST_ERROR_BIN_OUTPUT_INCORRECTO,
	ST_HELP,
	ST_ERROR_ARGUMENTOS_INVALIDOS,
	ST_ERROR_DIMENSION
} status_t;

typedef enum {
	LEER = 10,
	ESCRIBIR = 11,
	CARGAR = 20,
	GUARDAR = 21,
	PCARGAR = 22,
	PGUARDAR = 23,
	SUMAR = 30,
	RESTAR = 31,
	DIVIDIR = 32,
	MULTIPLICAR = 33,
	JMP = 40,
	JMPNEG = 41,
	JMPZERO = 42,
	JNZ = 43,
	DJNZ = 44,
	HALT = 45
} opcode_t;

#endif
